### ISSUE TITLE
Sphinx version compatibility w/ Python 3.7

### ISSUE THREAD

**Issue by KD-7** [comp0016-group1/truelearn#21]
I can downgrade our sphinx version to 5.3.0, however I wanted to know if these new features are necessary (releases 6 onwards),which could warrant the dropping of support for 3.7.
Please see: https://www.sphinx-doc.org/en/master/changes.html

**Comment by yuxqiu** [comment]
I'm not sure, because we don't explicitly use these functions in our code. I think maybe we should look at the plugins we are using.
